name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo apt-get update -qq && sudo apt-get install -qq gcc libc-dev curl make cpanminus
    - run: cpanm --sudo --notest --installdeps .
    - run: perl Makefile.PL
    - run: make
    - run: make distcheck
    - run: make test
